language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
script: ./deploy.sh
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
  - npm rebuild node-sass
branches:
  only:
  - master
  - staging
env:
  global:
  - ENCRYPTION_LABEL: "59e35e723000"
  - COMMIT_AUTHOR_EMAIL: "tataihono.nikora@gmail.com"
